---
OPTIMIZERS:
  ADADELTA:
    LR:
    WT_DECAY:
    RHO:
  ADAGRAD:
    LR:
    LR_DECAY:
    WT_DECAY:
  ADAM:
    LR:
    WT_DECAY:
    AMSGRAD:
  LBFGS:
    LR:
  RMS_PROP:
    LR:
    ALPHA:
    MOMENTUM:
    CENTERED:
    WT_DECAY:
  SGD:
    LR: 0.005
    MOMENTUM: 0.9
    WT_DECAY: 0.0005
LOSS:
  CROSS_ENTROPY_LOSS:
    REDUCTION: MEAN
  NLLLOSS:
    REDUCTION: MEAN
  BCELOSS:
    REDUCTION: MEAN
  MSELOSS:
    REDUCTION: MEAN
  L1LOSS:
    REDUCTION: MEAN
CNN:
  RESNET:
    DROPOUT:
HYPERPARAMETERS:
  OPTIMIZER: SGD
  LOSS: CROSS_ENTROPY_LOSS
  ACTIVATION: RELU
  LR: 0.005
  BATCH_SIZE: 256
  EPOCHS: 25
  DROPOUT: True
  BATCH_NORMALIZATION: True
  PADDING: True
  STRIDES: True
  GPU: True
  DEVICES: [0,1,2]
  PARALLEL: True
  PLOT_IMG: False
DATALOADER:
  DATA_DIR: "/Users/nikunjlad"
  STATS_PATH: "256_statistics_3.json"
  MODEL_PATH: "256_asl_3.pt"
  OUTPUT_PATH: "256_output_3"
  VALIDATION_SPLIT: 0.1
  ONE_HOT_ENCODE: False








